### ISSUE TITLE
Customer is not an AdSense Host

### ISSUE THREAD

**Issue by gabfr** [googleads/googleads-adsensehost-examples#1]
Hi,

I'm trying to integrate my platform with the AdSense Host API following the [holistic sample on the official documentation](https://developers.google.com/adsense/host/holisticsample).

You can find in my fork of this repository that I'm doing the integration in a separated file, called `adsensehost-association-sample.php` you can [check it out clicking here](https://github.com/gabfr/googleads-adsensehost-examples/blob/master/php-clientlib-1.x/v4.x/adsensehost-association-sample.php).

The OAuth process went ok (both with the Host account, and with the AdSense "test client" account), it does return the user code and I follow up with the process of [associationsessions.start](https://developers.google.com/adsense/host/v4.1/associationsessions/start).

But when I fill the form with the site URL to start the `associationsessions`, it prompt me the following exception: 
```
Fatal error: Uncaught Google_Service_Exception: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "noAdSenseHostAccount",
    "message": "Customer is not an AdSense Host."
   }
  ],
  "code": 403,
  "message": "Customer is not an AdSense Host."
 }
}
 in /home/vagrant/Projetos/googleads-adsensehost-examples/php-clientlib-1.x/v4.x/vendor/google/apiclient/src/Google/Http/REST.php on line 118
```

![screencapture-projetos-front-index-php-1508959679006](https://user-images.githubusercontent.com/1237163/32019127-eefabeaa-b9aa-11e7-8cda-9e6a7f142e27.png)

I don't know how to continue with the integration without being able to test the AssociationSession. It is a common error?

**Comment by DeanLukies** [comment]
Hi Gabfr,

I think this is an issue with (one of) your accounts rather than the example, you could email adsenseapi-tech@google.com for assistance.

cheers

**Comment by gabfr** [comment]
Thanks for your time @DeanLukies. WIll do it.
